apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 5Gi
    limits:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
spec:
  resources:
    requests:
      storage: 10Gi
    limits:
      storage: 10Gi
