apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium-with-limits
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Premium_LRS
  kind: Managed
  cachingmode: ReadOnly
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
