apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devsecops-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SamNwangwu/Azure-DevSecOps-Project.git
    targetRevision: main
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
