name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install frontend dependencies
      working-directory: ./app/frontend
      run: npm install
    
    - name: Run frontend tests
      working-directory: ./app/frontend
      run: npm test -- --passWithNoTests
    
    - name: Install backend dependencies
      working-directory: ./app/backend
      run: npm install
    
    - name: Run backend tests
      working-directory: ./app/backend
      run: npm test -- --passWithNoTests
    
    - name: Run Snyk Security Scan (Frontend)
      working-directory: ./app/frontend
      run: |
        npx snyk auth ${{ secrets.SNYK_TOKEN }}
        npx snyk test --severity-threshold=high || true
      continue-on-error: true
    
    - name: Run Snyk Security Scan (Backend)
      working-directory: ./app/backend
      run: |
        npx snyk auth ${{ secrets.SNYK_TOKEN }}
        npx snyk test --severity-threshold=high || true
      continue-on-error: true

    - name: Build Success
      run: echo "Build and security scans completed successfully"
